import makeFetchCookie from 'fetch-cookie'
const fetchCookie = makeFetchCookie(fetch)
const before = "mmsession=eyJpdiI6ImlRTndhdGdSZC83c1czWnhnMnhvRmc9PSIsInZhbHVlIjoidllDM2FEZi8zeE54K2tXNlc3eHpZMUYxYUpSM1pLYUp1RFdTMjhVK0R2WHpqRWNhSFVubmpvUlZWTVEzRjl2Ynh2VHo2ZFNYcE41eHhXcFl0OHk5YVlWZkRTVDRHRXhndnZxQndTOElmbVNoMVArV04zQ2pjNEV0dTdybURkZXYiLCJtYWMiOiJhYzgxNGE3MTVhYzc2MmVmNmJiN2Q1MWU3NGY1YWM3N2I2ZjgxNzE5MWU1Y2IwZjJlMDczYTAwMzU5MGU3YTRlIiwidGFnIjoiIn0%3D; canset=2025-04-16%2014%3A02%3A39; mm=eyJpdiI6InRpUkQxOVJSSmRJQWZuMm5LbGJ5VWc9PSIsInZhbHVlIjoieitmU09mNHZXWjlXVTlxRVJwRmFqbVU3WU9yRDNuelVmRjZINWtDUjRxM2IrK1VaaVk4NXArZm1UNGJwREtPeitaYis5dEp1dXV2dnlRdXNiWXM5MDFpckdoMFl6R3ZKN0VvMFdzQ1VRMUZSU3A4T0ZIdWc4UmhlRVphSk95VWpVUTNJRlNmcVlQZ3V4UnZZY2UzeW5WZXlyZHBaYnBIT1lBaHAyb29KN0FUZFlEM25iZUJ2YjZ3REdNSlcrZTZtaXRJRkpNMmtseXFzM3RXUlJqSFVXakZxck9TZ3hIMUY4dUZUVkIwazBVWT0iLCJtYWMiOiI0ZjQ4ZmEyOTAzMjc1MzVkZDE4NTkxN2RkYjcxYjBjYzM5MjQzYzMzOTJiZjE5OWU1NmFiZTZiMDQ0NGRiNjBlIiwidGFnIjoiIn0%3D; mmsession_t1=120; mmsession_t2=r0HvXTUKo56Ee4KDGEBcwsaVDSC0t01jPhJ3JPFL"
fetchCookie.cookieJar.setCookie(before, "https://membermojo.co.uk")

const upstream = await fetchCookie("https://membermojo.co.uk/vcgh/signin_password", {
    body: `email=timrog@gmail.com&password=@c7g.A<y.$adDc)p[DZg`,
    method: "POST"
})

console.log(upstream.headers)

const after = await fetchCookie.cookieJar.getCookieString("https://membermojo.co.uk")

console.log(before)
console.log(after)


/*

curl -sS --cookie cookies.txt --cookie-jar cookies.txt --output signin.html --data 'email=timrog@gmail.com&password=@c7g.A<y.$adDc)p[DZg' https://membermojo.co.uk/vcgh/signin_password
curl -sS --cookie cookies.txt --output members.csv https://membermojo.co.uk/vcgh/membership/download_members

curl -sS --cookie cookies.txt --cookie-jar cookies.txt 'https://membermojo.co.uk' | sed -En 's/^.*"csrf_token":"([^"]+).*$/\1/p'

curl -sS --cookie cookies.txt --cookie-jar cookies.txt --output verify.html --data 'csrf_token=<csrf-token>' '<verification-link>'

*/

# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

    membermojo.co.uk        FALSE / TRUE    1744820575      mmsession_t2    p11DiXRFKiloXuFzhGObuJrD6CMSNJsrls1tU08Z
membermojo.co.uk        FALSE / TRUE    1744820449      mmsession_t1    120
membermojo.co.uk        FALSE / TRUE    1744820575      canset  2025-04 - 16 % 2016 % 3A12 % 3A55
#HttpOnly_membermojo.co.uk      FALSE / FALSE   1744820575      mmsession       eyJpdiI6ImRsQkF5VVBnV25JSFNSYllMdzc1NEE9PSIsInZhbHVlIjoiSXh4VWJhbDBGWEFaSzdUczU2U2d3Z0k2eHJEaXpXNjlDRWs3VnN6TEpKQ0xmOVNOOS9QMk1yWCtHaERyT3dUbUw0VWQwWTBSSXlGV1l6RWpEdXYvYkFrbmZRdE02a3pZUkZYOXAya3lHcFEzVC9wdllTaVNmTUtZVGE2QXp1cmwiLCJtYWMiOiIwNDQyMDI5NWM5NGY0N2U1ZTA3ZjBhYzE3ZTRjZGRmZWIzOWFmMDU3NmQ4YzdmYTViMjVkODFiMmVhMWVlMjg5IiwidGFnIjoiIn0 % 3D
#HttpOnly_membermojo.co.uk      FALSE / TRUE    1779376375      mm      eyJpdiI6ImlBU01JNFlUWElnTDA5ZUZXeFFrZUE9PSIsInZhbHVlIjoiV0Z1WVByc0d1eEZENW8zaHZaSjIycjBnY2prS2h0RThKeStIV1VLekhBZEloeVFJLzRuejBuVlhiMmRRbTl6WElTUE0yMFhwYzVmL1lpbGdhQlpVRm1rV0kvVExiREJObXY3dWlnWFZFRlpxS0hzd3NUT2lLelRFYlMzQUtnTDRwL3ZDUU5SVlk4LzI5TUM4RmQ2RllHZmMrWHk1Y1c3ODlBQ2xJZjVnTVd3Z1ZRK044NDY2MlNXSVJjOVVsMThrTWN5cmtqajZ6Ukw0T1FYRStBZ0lyWE5SQTM0VGZmcG5VUFd3L2VlWHRkcz0iLCJtYWMiOiIzNDc3NDhiMzNkMDVhZDI0OWE3ZDRjY2IzOTlhZmIyYjcyYWNmNjhiN2I1ZmU4ZDg5ZGNiNTM1NWYyMThkMTA5IiwidGFnIjoiIn0 % 3D
#HttpOnly_membermojo.co.uk      FALSE / FALSE   1779376375      remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d   eyJpdiI6ImdCZHFNTHZ4NUxXWDRXUzZKVWIvZ3c9PSIsInZhbHVlIjoiVjlLMDdaOVN6d3hPUXkyS2RvRFJCNVM3bmc3WlJJcVBWeTA3KzFEbTEyMDZrQTIvWHFmT3lKbno1ZTJCREZUSGZpZm9Cc01telFxcGIrK2xoYm1aWHMybkVKV2t4MERadWRjMm1haUJEcEUycFZUSlhqOXlSYW1VMzVzclpuSXpVNFVSamRsL0RvMkVKVnBYSU92LzNycHU0dHRVbmExQTBsMnl5MVVWRGE1T2ZJcis3cU1iSGxIc1hOWDBEK2RJdHpZRGxSWXBrb1J5VndQbW1iUkVnQW1wM1ZzRCtyV3JrN0xLUEx4Y1h4OD0iLCJtYWMiOiJhYTk3NzcyYzdjM2U2YTA1OWE3NjI3M2I0ZjA0N2EyMzllYmFlYWQ5OTFmNzhhNzY3YTFiMGU1Mjg1ODRlMjYyIiwidGFnIjoiIn0 % 3D
#HttpOnly_membermojo.co.uk      FALSE / TRUE    1752592375      trust_f577e5410d888ccbc7d1d48c910b7663631e26d27e6190bc602c95824bb709b5  eyJpdiI6ImRmWVplYVAzYTFQSmhaUVVyM05vQVE9PSIsInZhbHVlIjoiMVoxZXdud3ZaamZkU2lQZCsxbUo0dnVMQW9YQ3dxSnlPT3k4NEhGdlpiZ0IyU1VleXZ6UDc5K0lRZEFVV2lZdmZ4MkNIUHdKSjhKdTVyUDh5bHVoVzJlZW10U3hGck1VQUoybnhTbEcvVGRhMXJIckRQV3ZOaTBmbnVGOHZaNEh4cWdyN1JRNmNaZVIrZHJMUG1jUWI3VVRjbndPWUhIUmx6dmxtRFBrbWpVPSIsIm1hYyI6ImNlYzNlZTY1OWFhODU3MTI3OTg5M2VmZGE5NGMyY2RlNGY1NjUyNjAwYmQ3MjhiOTgzYjM5YWM5M2NhMjcxY2UiLCJ0YWciOiIifQ % 3D % 3D