import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import 'bootstrap/dist/css/bootstrap.min.css'
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp"
import { initFirebase } from "@/lib/firebase/initFirebase"
import { Nav, Navbar, NavbarBrand, NavbarCollapse, NavbarToggle, NavItem, NavLink } from "react-bootstrap"
import StyledJsxRegistry from "./registry"
import FirebaseAuth from "./firebaseAuth"
import { User } from "firebase/auth"
initFirebase()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const { currentUser } = await getAuthenticatedAppForUser()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledJsxRegistry>
          <header>
            <Navbar bg="primary">
              <NavbarBrand>
                <img src="https://vcgh.co.uk/wp-content/uploads/2024/06/Banner-trans.svg" alt="Logo" height="40" />
              </NavbarBrand>
              <NavItem>
                <NavLink href="/">Events</NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="/create">Post a ride</NavLink>
              </NavItem>
              <FirebaseAuth initialUser={currentUser.toJSON() as User} />
              <NavbarToggle aria-controls="basic-navbar-nav" />
            </Navbar>
          </header>
          <main>
            {children}
          </main>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}


