import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp"
import { initFirebase } from "@/lib/firebase/initFirebase"
import FirebaseAuth from "./firebaseAuth"
import { User } from "firebase/auth"
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, NavbarMenuToggle } from "@heroui/navbar"
import Link from "next/link"
import { Providers } from "./providers"
initFirebase()

const sansFont = Poppins({
  variable: "--font-sans",
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const { currentUser } = await getAuthenticatedAppForUser()
  return (
    <html lang="en">
      <body className={sansFont.variable}>
        <Providers>
          <div className="relative flex flex-col h-screen">
            <Navbar isBordered isBlurred className="bg-primary">
              <NavbarBrand>
                <img src="https://vcgh.co.uk/wp-content/uploads/2024/06/Banner-trans.svg" alt="Logo" width="150" />
              </NavbarBrand>
              <NavbarContent className="hidden sm:flex gap-4" justify="center">
                <NavbarItem>
                  <Link href="/">Events</Link>
                </NavbarItem>
                <NavbarItem>
                  <Link href="/create">Post a ride</Link>
                </NavbarItem>
              </NavbarContent>
              <NavbarContent justify="end">
                <FirebaseAuth initialUser={currentUser?.toJSON() as User} />
                <NavbarMenuToggle aria-controls="basic-navbar-nav" />
              </NavbarContent>
            </Navbar>
            <main className="flex-1 container mx-auto px-4 py-8">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}


