import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import 'bootstrap/dist/css/bootstrap.min.css'
import FirebaseAuth from "../components/auth/FirebaseAuth"
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp"
import { initFirebase } from "@/lib/firebase/initFirebase"
import { Nav, Navbar, NavbarBrand, NavbarCollapse, NavbarToggle, NavLink } from "react-bootstrap"
initFirebase()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const { currentUser } = await getAuthenticatedAppForUser()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Navbar bg="primary">
            <NavbarBrand>
              <img src="https://vcgh.co.uk/wp-content/uploads/2024/06/Banner-trans.svg" alt="Logo" height="40" />
            </NavbarBrand>
            <NavbarToggle aria-controls="basic-navbar-nav" />
            <NavbarCollapse id="basic-navbar-nav">
              <Nav className="me-auto">
                <NavLink href="/">Events</NavLink>
                <NavLink href="/create">Post a ride</NavLink>
              </Nav>
              <FirebaseAuth initialUser={currentUser?.toJSON()} />
            </NavbarCollapse>
          </Navbar>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
